apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: k8s
spec:
  selector:
    matchLabels:
      app: k8s
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: k8s
    spec:
      containers:
        - name: k8s 
          image: nguyenthanhdat1810/k8s:latest
          # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
# The port that the container is running on in the cluster